- name: Install and configure MariaDB
  hosts: all
  tasks:
    - name: Install MariaDB server
      dnf:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        enabled: yes
        state: started

